#!/usr/bin/env bash
# Run the Landing exploration notebook headless and keep a log of the run.
# Run from the repo root: bash scripts/run_exploration.sh
# Regenerates evidence/landing_* and writes evidence/landing_exploration_run.log.
set -euo pipefail

LOG=evidence/landing_exploration_run.log
PY=${PYTHON:-.venv/bin/python}
OUT=$(mktemp -d)

{
  echo "run_ts:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "commit:   $(git rev-parse --short HEAD)"
  echo "python:   $($PY --version 2>&1)"
  echo "pyspark:  $($PY -c 'import pyspark; print(pyspark.__version__)')"
  echo "java:     $(java -version 2>&1 | head -1)"
  echo "landing:  ${DATA_LANDING:-data/landing}"
  echo
  start=$(date +%s)
  $PY -m jupyter nbconvert --to notebook --execute \
    --output-dir "$OUT" notebooks/01_landing_exploration.ipynb 2>&1 \
    | tr '\r' '\n' | grep -v -e '^\s*$' -e '\[Stage '
  echo "elapsed:  $(( $(date +%s) - start )) s"
  echo
  echo "evidence files:"
  wc -l evidence/landing_profile.md evidence/landing_source_profile.csv evidence/landing_column_profile.csv
  echo
  echo "evidence diff against the committed version, ignoring the run date (empty means reproduced):"
  git diff --stat -I '^Generated by' -- evidence/landing_profile.md evidence/landing_source_profile.csv evidence/landing_column_profile.csv
} | tee "$LOG"

rm -rf "$OUT"
